language: python
sudo: false
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install python-coveralls tox tox-travis
script: tox --recreate
after_success:
- pip install -r requirements.txt -e .
- py.test --cov=ddd_api_gateway --cov-report=term-missing tests
- coveralls
deploy:
  provider: pypi
  user: sunzhongmou
  password:
    secure: pai3O4/T/nDleRjtR6RxJP0IrxMaCALjHirm1PairjYYS03/HE0o1W39mYv+HMdK7Dy6YUpetUukxQ3TncNR77RvE32dloZSu7ivqSdHZc7/KvKV3u2prOSSsdARSuZem5/wf5FSx4pVr1Vn6VzRfTX0MwiRSz5CkgukCxgjYzt56iqMC11tlztkZ/5vyea0YHSjss6PCk63OzYreWYaY5t4CUocdhYJXflJRAB/jXLpXik0KZIyvlW75hDaSRwUBdSfkPLcKJD04ScsSaVnuHSrrJzM2mAB6oF9l8AxDVTDnwb6yQbO2g8s3vlSNIMdYUlUu81togDUBzADZ1kc0Ic4g7fAL1M0AUY1P8gTunwlITOCZD2QRmgC5NsvSuB1O2Kuuj3hN5ani6dwfZXnV6kzxwEIlNK7QqUHla7VwRslPgtMGHbJNcZCWmldlMnwGSixg9MTVy98xCWgK2WAq0eSa1si7mO8VCrULj5R/re6GmwrO7hPlPeB9qSVALLvc2Ox8QSzSvl/gaoDlWGLlah6vOd2JyPlonglpL6IeNDFb/IUUCpG/Vd3fYgYMTnJScQvyY8iU84ZCM/XS73KFJwfOEl4vzHfM3orQJT6hqchZanAsf1kH02Ar5XyWqBJtdpZNgvAw4onGDFzvoYX0nfz1SsstKwJEthxIojiiOo=
  on:
    python: 2.7
  skip_existing: true
